// {{cookiecutter.project_slug}}/clients/web/react/src/pages/dashboard.tsx
export const Dashboard = () => {
  return (
    <div className="flex min-h-full flex-1 flex-col">
      <header className="bg-primary relative mx-auto flex h-32 w-full flex-col justify-center sm:h-48">
        <div className="mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8">
          <h1 className="heading mb-0 text-left font-bold uppercase text-white">Dashboard</h1>
        </div>
      </header>
      <div className="h-full min-h-full p-4 sm:px-16 sm:py-4">Content goes here...</div>
    </div>
  )
}

// {{cookiecutter.project_slug}}/clients/web/vue3/src/views/Dashboard.vue
<script lang="ts" setup></script>

<template>
  <div class="flex min-h-full flex-1 flex-col">
    <header class="relative mx-auto flex h-32 w-full flex-col justify-center bg-primary sm:h-48">
      <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 w-full">
        <h1 class="heading mb-0 text-left font-bold uppercase text-white">Dashboard</h1>
      </div>
    </header>
    <div class="h-full min-h-full p-4 sm:px-16 sm:py-4">Content goes here...</div>
  </div>
</template>
