// {{cookiecutter.project_slug}}/clients/web/react/src/pages/request-password-reset.tsx
import { useMutation } from '@tanstack/react-query'
import { FormProvider, useTnForm } from '@thinknimble/tn-forms-react'
import { useState } from 'react'
import { useNavigate } from 'react-router'
import { AuthLayout } from 'src/components/auth-layout'
import { Button } from 'src/components/button'
import { ErrorMessage, ErrorsList } from 'src/components/errors'
import { Input } from 'src/components/input'
import {
  EmailForgotPasswordForm,
  EmailForgotPasswordInput,
  TEmailForgotPasswordForm,
  userApi,
} from 'src/services/user'
import { getErrorMessages } from 'src/utils/errors'

export const RequestPasswordResetInner = () => {
  const [errorMessage, setErrorMessage] = useState<string[] | undefined>()
  const [resetLinkSent, setResetLinkSent] = useState(false)
  const { createFormFieldChangeHandler, form } = useTnForm<TEmailForgotPasswordForm>()
  const navigate = useNavigate()

  const { mutate: requestReset } = useMutation({
    mutationFn: userApi.csc.requestPasswordReset,
    onSuccess: () => {
      setErrorMessage(undefined)
      setResetLinkSent(true)
    },
    onError(e: any) {
      const errors = getErrorMessages(e)
      setErrorMessage(errors)
    },
  })

  const handleRequest = () => {
    const input = {
      email: form.email.value ?? '',
    }
    requestReset(input)
  }

  return (
    <AuthLayout title="Request Password Reset">
      <div className="mt-6 sm:mx-auto sm:w-full sm:max-w-sm">
        {resetLinkSent ? (
          <>
            <p className="text-md">
              Your request has been submitted. If there is an account associated with the email
              provided, you should receive an email momentarily with instructions to reset your
              password.
            </p>
            <p className="text-md">
              If you do not see the email in your main folder soon, please make sure to check your
              spam folder.
            </p>
            <div className="pt-6">
              <Button
                onClick={() => {
                  navigate('/log-in')
                }}
                variant="primary"
              >
                Return to Login
              </Button>
            </div>
          </>
        ) : (
          <>
            <form
              onSubmit={(e) => {
                e.preventDefault()
              }}
              className="flex flex-col gap-2"
            >
              <Input
                placeholder="Enter email..."
                onChange={(e) => createFormFieldChangeHandler(form.email)(e.target.value)}
                value={form.email.value ?? ''}
                data-cy="email"
                id="id"
                label="Email address"
              />
              <ErrorsList errors={form.email.errors} />
              <div className="mb-2">
                <ErrorMessage>{errorMessage}</ErrorMessage>
              </div>
              <Button onClick={handleRequest} disabled={!form.isValid} variant={'primary'}>
                Request Password Reset
              </Button>
            </form>
          </>
        )}
      </div>
    </AuthLayout>
  )
}

export const RequestPasswordReset = () => {
  return (
    <FormProvider<EmailForgotPasswordInput> formClass={EmailForgotPasswordForm}>
      <RequestPasswordResetInner />
    </FormProvider>
  )
}

// {{cookiecutter.project_slug}}/clients/web/vue3/src/views/RequestPasswordReset.vue
<template>
  <div class="flex min-h-full flex-1 flex-col justify-center px-6 py-12 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
      <img class="mx-auto h-12 w-auto" src="@/assets/icons/glyph.svg" alt="ThinkNimble" />
      <h2 class="mt-4 text-center text-2xl font-bold leading-9 tracking-tight text-primary">
        Request Password Reset
      </h2>
    </div>
    <div class="mt-6 sm:mx-auto sm:w-full sm:max-w-sm">
      <template v-if="!resetLinkSent">
        <form @submit.prevent="attemptResetRequest()">
          <InputField
            v-model:value="form.email.value"
            :errors="form.email.errors"
            @blur="form.email.validate()"
            data-cy="email"
            type="email"
            label="Email address"
            placeholder="Enter email..."
          />
          <button
            :class="form.isValid ? 'btn--primary bg-primary' : 'btn--disabled bg-gray-200'"
            data-cy="submit"
            type="submit"
          >
            Request Password Reset
          </button>
        </form>
      </template>
      <template v-if="resetLinkSent">
        <p class="text-md" data-cy="submit-success">
          Your request has been submitted. If there is an account associated with the email
          provided, you should receive an email momentarily with instructions to reset your
          password.
        </p>
        <p class="text-md">
          If you do not see the email in your main folder soon, please make sure to check your spam
          folder.
        </p>
        <div class="pt-6">
          <button type="button" class="btn--primary bg-primary">
            <router-link :to="{ name: 'Login' }" class="" id="login-link">
              Return to Login
            </router-link>
          </button>
        </div>
      </template>
    </div>
  </div>
</template>

<script>
import { ref } from 'vue'
import { userApi, RequestPasswordResetForm } from '@/services/users/'
import InputField from '@/components/inputs/InputField.vue'

export default {
  name: 'RequestPasswordReset',
  components: {
    InputField,
  },
  setup() {
    const form = ref(new RequestPasswordResetForm())
    const resetLinkSent = ref(false)

    function handleResetRequestSuccess(data) {
      resetLinkSent.value = true
      console.log('success', data)
    }

    function handleResetRequestFailure(error) {
      alert(error)
    }

    function attemptResetRequest() {
      // unwrap form
      const unwrappedForm = form.value
      unwrappedForm.validate()
      if (!unwrappedForm.isValid) return

      userApi.csc
        .requestPasswordReset({ email: unwrappedForm.email.value })
        .then(handleResetRequestSuccess)
        .catch(handleResetRequestFailure)
    }

    return {
      form,
      attemptResetRequest,
      resetLinkSent,
    }
  },
}
</script>
