// {{cookiecutter.project_slug}}/clients/web/react/src/components/button.tsx
import { ButtonHTMLAttributes, FC, ReactNode } from 'react'
import { Link, LinkProps } from 'react-router-dom'
import { Spinner } from './spinner'

type ButtonVariant = 'primary' | 'accent' | 'disabled'
const buttonVariantMap: Record<ButtonVariant, string> = {
  primary:
    'flex w-full cursor-pointer items-center justify-center rounded-md border px-3 py-2 text-sm font-semibold shadow-sm border-primary text-white hover:bg-primaryLight bg-primary',
  accent: '',
  disabled:
    'flex w-full cursor-pointer items-center justify-center rounded-md border px-3 py-2 text-sm font-semibold shadow-sm cursor-not-allowed border-gray-200 bg-gray-200',
}

type CommonButtonProps = {
  variant?: ButtonVariant
  extendClassName?: string
}
export const Button: FC<
  CommonButtonProps &
    (
      | ({ link?: undefined; isLoading?: boolean } & ButtonHTMLAttributes<HTMLButtonElement>)
      | {
          link: LinkProps
          children: ReactNode
        }
    )
> = ({ extendClassName = '', children, variant = 'primary', ...props }) => {
  if ('link' in props && props.link) {
    return (
      <Link
        className={` rounded-lg transition-transform hover:scale-[1.05] disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:transform-none ${buttonVariantMap[variant]} ${extendClassName}`}
        {...props.link}
      >
        {children}
      </Link>
    )
  } else {
    const { isLoading, ...rest } = props
    return (
      <button
        {...rest}
        className={` rounded-lg transition-transform hover:scale-[1.05] hover:shadow-lg disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:transform-none ${buttonVariantMap[variant]} ${extendClassName}`}
        disabled={props.disabled || isLoading}
      >
        {props.isLoading ? <Spinner size="sm" /> : children}
      </button>
    )
  }
}

// {{cookiecutter.project_slug}}/clients/web/vue3/src/components/Button.vue
<script setup lang="ts">
import LoadingSpinner from '@/components/LoadingSpinner.vue'
import { ButtonHTMLAttributes } from 'vue'

type ButtonVariant = 'primary' | 'secondary' | 'unstyled'

interface ButtonProps extends /* @vue-ignore */ ButtonHTMLAttributes {
  variant?: ButtonVariant
  extendClass?: string
  isLoading?: boolean
}

const buttonVariantClassMap: Record<
  ButtonVariant,
  {
    buttonClass: string
    spinnerColor?: string
  }
> = {
  primary: { buttonClass: 'bg-primary text-white', spinnerColor: 'white' },
  secondary: { buttonClass: 'bg-secondary text-black hover:bg-primary hover:text-white' },
  unstyled: {
    buttonClass: '',
  },
}

const props = withDefaults(defineProps<ButtonProps>(), {
  variant: 'primary',
})
</script>

<template>
  <button
    :class="`py-2 px-3 rounded-lg font-semibold disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer flex items-center justify-center hover:ease-in hover:transition-transform hover:scale-[0.95] ${
      buttonVariantClassMap[props.variant].buttonClass
    } ${props.extendClass}`"
    :disabled="props.isLoading"
  >
    <LoadingSpinner
      v-if="props.isLoading"
      class="w-4"
      :color="buttonVariantClassMap[props.variant].spinnerColor"
    />
    <slot v-else />
  </button>
</template>
