// {{cookiecutter.project_slug}}/clients/web/vue3/src/views/PageNotFound.vue
<template>
  <main class="grid h-full flex-auto place-items-center bg-white px-6 py-24 sm:py-32 lg:px-8">
    <div class="text-center">
      <p class="font-semibold text-accent">404</p>
      <h1 class="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">Page not found</h1>
      <p class="mt-6 leading-7">Sorry, we couldn't find the page you're looking for.</p>
      <div class="mt-10 gap-x-6">
        <router-link
          to="/"
          class="rounded-md bg-accent px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-primary focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"
          >Go back home</router-link
        >
      </div>
    </div>
  </main>
</template>

<script>
export default {
  name: 'PageNotFound',
}
</script>

// {{cookiecutter.project_slug}}/clients/web/react/src/pages/page-not-found.tsx
import { Link } from 'react-router-dom'

export const PageNotFound = () => {
  return (
    <main className="grid h-full flex-auto place-items-center bg-white px-6 py-24 sm:py-32 lg:px-8">
      <div className="text-center">
        <p className="font-semibold text-accent">404</p>
        <h1 className="mt-4 text-3xl font-bold tracking-tight sm:text-5xl">Page not found</h1>
        <p className="mt-6 leading-7">
          Sorry, we couldn&apos;t find the page you&apos;re looking for.
        </p>
        <div className="mt-10 gap-x-6">
          <Link
            to="/home"
            className="rounded-md bg-accent px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-primary focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"
          >
            Go back home
          </Link>
        </div>
      </div>
    </main>
  )
}
