// {{cookiecutter.project_slug}}/clients/web/vue3/src/views/Signup.vue
<template>
  <div class="flex min-h-full flex-1 flex-col justify-center px-6 py-10 lg:px-8">
    <div class="sm:mx-auto sm:w-full sm:max-w-sm">
      <img class="mx-auto h-12 w-auto" src="@/assets/icons/glyph.svg" alt="ThinkNimble" />
      <h2 class="mt-4 text-center text-2xl font-bold leading-9 tracking-tight text-primary">
        Sign up
      </h2>
    </div>

    <div class="mt-6 sm:mx-auto sm:w-full sm:max-w-sm">
      <form @submit.prevent="attemptUserRegistration()">
        <div>
          <label class="mb-2 block text-left text-sm font-medium leading-6 text-primary"
            >First Name</label
          >
          <InputField
            v-model:value="form.firstName.value"
            :errors="form.firstName.errors"
            @blur="form.firstName.validate()"
            placeholder="Enter first name..."
          />
        </div>

        <div>
          <label class="mb-2 block text-left text-sm font-medium leading-6 text-primary"
            >Last Name</label
          >
          <InputField
            v-model:value="form.lastName.value"
            :errors="form.lastName.errors"
            @blur="form.lastName.validate()"
            placeholder="Enter last name..."
          />
        </div>

        <div>
          <label class="mb-2 block text-left text-sm font-medium leading-6 text-primary"
            >Email</label
          >
          <InputField
            v-model:value="form.email.value"
            :errors="form.email.errors"
            @blur="form.email.validate()"
            type="email"
            placeholder="Enter email..."
          />
        </div>

        <div>
          <label class="mb-2 block text-left text-sm font-medium leading-6 text-primary"
            >Password</label
          >
          <InputField
            v-model:value="form.password.value"
            :errors="form.password.errors"
            @blur="form.password.validate()"
            type="password"
            placeholder="Enter password..."
          />
        </div>
        <div>
          <label class="mb-2 block text-left text-sm font-medium leading-6 text-primary"
            >Confirm Password</label
          >
          <InputField
            v-model:value="form.confirmPassword.value"
            :errors="form.confirmPassword.errors"
            @blur="form.confirmPassword.validate()"
            type="password"
            placeholder="Confirm Password"
          />
        </div>
        <div>
          <button type="submit" data-cy="submit" class="btn--primary bg-primary">Sign up</button>
        </div>
      </form>
    </div>
    <div class="m-4 flex self-center text-sm">
      <p class="mr-2">Already have an account?</p>
      <router-link :to="{ name: 'Login' }" class="font-bold text-primary hover:underline">
        Log in.
      </router-link>
    </div>
  </div>
</template>

<script>
import InputField from '@/components/inputs/InputField.vue'
import { SignupForm, userApi } from '@/services/users/'
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useStore } from 'vuex'

export default {
  name: 'Signup',
  components: {
    InputField,
  },
  setup() {
    const store = useStore()
    const router = useRouter()
    const form = ref(new SignupForm())

    async function handleRegistrationSuccess(user) {
      await store.dispatch('setUser', user)
      const redirectPath = router.currentRoute.value.query.redirect
      if (redirectPath) {
        router.push({ path: redirectPath })
      } else {
        router.push({ name: 'Dashboard' })
      }
    }

    function handleRegistrationFailure(error) {
      alert(error)
    }

    function attemptUserRegistration() {
      // unwrap form
      const unwrappedForm = form.value
      unwrappedForm.validate()
      if (!unwrappedForm.isValid) return

      userApi
        .create({
          firstName: unwrappedForm.firstName.value,
          lastName: unwrappedForm.lastName.value,
          email: unwrappedForm.email.value,
          password: unwrappedForm.password.value,
        })
        .then(handleRegistrationSuccess)
        .catch(handleRegistrationFailure)
    }

    return {
      form,
      attemptUserRegistration,
    }
  },
}
</script>

<style scoped lang="css"></style>

// {{cookiecutter.project_slug}}/clients/react/src/pages/sign-up.tsx
import { useMutation } from '@tanstack/react-query'
import { FormProvider, useTnForm } from '@thinknimble/tn-forms-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useNavigate } from 'react-router-dom'
import { Button } from 'src/components/button'
import { ErrorsList } from 'src/components/errors'
import { Input } from 'src/components/input'
import { SignupForm, TSignupForm } from 'src/forms'
import { SignupInputs } from 'src/forms/signup'
import { postCreateUser, postLogin } from 'src/services/auth'
import { localStoreManager } from 'src/utils/local-store-manager'
import { useAuth } from '../utils/auth'

function SignUpInner() {
  const [error, setError] = useState('')
  const { updateToken } = useAuth()
  const { form, createFormFieldChangeHandler, validate } = useTnForm<TSignupForm>()
  const navigate = useNavigate()

  const { mutate: logIn } = useMutation(postLogin, {
    onSuccess: (data: { tokenAuth: { token: string } }) => {
      localStoreManager.token.set(data.tokenAuth.token)
      updateToken(data.tokenAuth.token)
      navigate('/home')
    },
    onError: () => {
      navigate('/log-in', {
        state: {
          autoError: 'There was a problem logging you in. Please try again.',
        },
      })
    },
  })

  const { mutate: createUser } = useMutation(postCreateUser, {
    onSuccess: (data) => {
      logIn({
        email: form.email.value ?? '',
        password: form.confirmPassword.value ?? '',
      })
    },
    onError: (error: { message: string }) => {
      console.error(error)
    },
  })

  const onSubmit = () => {
    createUser({
      email: form.email.value ?? '',
      password: form.password.value ?? '',
      firstName: form.firstName.value ?? '',
      lastName: form.lastName.value ?? '',
    })
  }

  return (
    <main className="bg-slate-800 h-screen flex flex-col justify-center items-center gap-3">
      <header className="text-white text-xl">WELCOME</header>
      <p className="text-white text-md">Enter your details below to create an account</p>
      <form onSubmit={onSubmit} className="flex flex-col gap-3">
        <div className="flex flex-col gap-3">
          <div>
            <Input
              placeholder="First Name"
              onChange={(e) => {
                createFormFieldChangeHandler(form.firstName)(e.target.value)
              }}
            />
            <ErrorsList errors={form.firstName.errors} />
          </div>
          <div>
            <Input
              placeholder="Last Name"
              onChange={(e) => {
                createFormFieldChangeHandler(form.lastName)(e.target.value)
              }}
            />

            <ErrorsList errors={form.lastName.errors} />
          </div>
        </div>
        <div>
          <Input
            type="email"
            placeholder="Email"
            onChange={(e) => {
              createFormFieldChangeHandler(form.email)(e.target.value)
            }}
          />
          <ErrorsList errors={form.email.errors} />
        </div>

        <div>
          <Input
            placeholder="Password"
            type="password"
            onChange={(e) => {
              createFormFieldChangeHandler(form.password)(e.target.value)
            }}
          />
          <ErrorsList errors={form.password.errors} />
        </div>
        <div>
          <Input
            id="confirmPassword"
            placeholder="Confirm Password"
            type="password"
            onChange={(e) => {
              createFormFieldChangeHandler(form.confirmPassword)(e.target.value)
            }}
          />
          <ErrorsList errors={form.confirmPassword.errors} />
        </div>
        <Button type="submit">Sign Up</Button>
      </form>

      <div className="flex flex-col gap-3">
        <p className="text-xl text-slate-200 font-semibold">Already have an account?</p>
        <Link to="/log-in" className="text-xl text-teal-600 font-semibold text-center">
          Log in here
        </Link>
      </div>
    </main>
  )
}

export const SignUp = () => {
  return (
    <FormProvider<SignupInputs> formClass={SignupForm}>
      <SignUpInner />
    </FormProvider>
  )
}
